name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      # Checks-out Java
      - uses: actions/setup-java@v2
        with:
          distribution: microsoft
          java-version: 17

      # Identifies all relevant Java files that have been changed in latest commit
      - name: Change Java
        uses: tj-actions/changed-files@v13.1
        id: change-java
        with:
          files: |
            pom.xml
            **/*.java

      # Runs type checker for Java files
      - name: Build Java files
        run: |
          timeout 2m mvn site

      - name: Run Unit tests
        run: timeout 2m mvn test

          


